import {chromium,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});
const context=await browser.newContext({permissions:[]});const page=await context.newPage();page.setDefaultTimeout(20000);
const results=[];const step=async(name,fn)=>{try{await fn();results.push({name,status:'pass'});}catch(e){results.push({name,status:'fail',reason:e.message.slice(0,500)});}console.log(results.at(-1));};
try{
 await page.goto('http://127.0.0.1:4311/');
 await step('geolocation denied retains manual search',async()=>{await context.grantPermissions([],{origin:'http://127.0.0.1:4311'});await page.getByRole('button',{name:/Use my location/}).click();await expect(page.locator('body')).toContainText(/denied|permission|could not|unavailable/i,{timeout:20000});await expect(page.locator('#city-search')).toBeEnabled();});
 await step('forecast provider failure stays isolated',async()=>{await page.route('**/api/v1/forecast?**',r=>r.fulfill({status:502,contentType:'application/json',body:JSON.stringify({status:'error',code:'provider_error',message:'Browser test: forecast unavailable'})}));await page.locator('#city-search').fill('Honolulu');await page.locator('.search-results button').first().click();await expect(page.getByRole('button',{name:'Retry forecast'})).toBeVisible();await expect(page.getByRole('tab',{name:'Maps',exact:true})).toBeEnabled();await page.unroute('**/api/v1/forecast?**');await page.getByRole('button',{name:'Retry forecast'}).click();await expect(page.locator('.hero-temperature')).toBeVisible();});
 await step('radar provider failure stays isolated',async()=>{await page.route('**/api/v1/maps/frame?**',r=>r.fulfill({status:502,contentType:'application/json',body:JSON.stringify({status:'error',code:'provider_error',message:'Browser test: map unavailable'})}));await page.getByRole('tab',{name:'Maps',exact:true}).click();await expect(page.locator('.maps-panel')).toContainText('Browser test: map unavailable');await expect(page.locator('.map-controls select').first()).toBeEnabled();await page.unroute('**/api/v1/maps/frame?**');await page.getByRole('button',{name:'Refresh catalog & frame',exact:true}).click();await expect(page.locator('.interactive-map')).toHaveAttribute('data-weather-ready','true');});
 await step('Alaska radar and explicit global infrared',async()=>{await page.locator('.map-controls select').first().selectOption('AK');await expect(page.locator('.interactive-map')).toHaveAttribute('data-weather-ready','true');await expect(page.locator('.maps-panel')).toContainText('GOES');await page.locator('.map-controls select').nth(1).selectOption('satellite-global-infrared');await expect(page.locator('.interactive-map')).toHaveAttribute('data-weather-ready','true');await page.locator('.interactive-map').screenshot({path:'docs/verification/browser/alaska-global.png'});});
 await step('Hawaii radar',async()=>{await page.locator('.map-controls select').first().selectOption('HI');await expect(page.locator('.interactive-map')).toHaveAttribute('data-weather-ready','true');await page.locator('.interactive-map').screenshot({path:'docs/verification/browser/hawaii-radar.png'});});
}finally{await writeFile('docs/verification/browser/failure-results.json',JSON.stringify({time:new Date().toISOString(),browser:browser.version(),results,notes:'Forecast/map failure steps deliberately inject explicit error responses into this test browser only; all success weather uses deployed live API.'},null,2));await browser.close();}
