import {test} from 'node:test';import assert from 'node:assert/strict';
import {VerificationRepository} from '@zindycast/verification';import {SharedStorage,APP_PROVIDER_LIMITS} from '@zindycast/storage';import {ForecastSchema} from '@zindycast/contracts';
import {createVerificationWorker} from './verification-runtime.js';
test('production verification wiring captures baseline and named candidates under quota without raw heat payloads',async()=>{
 const verification=new VerificationRepository({path:':memory:'}),storage=new SharedStorage({path:':memory:',providers:APP_PROVIDER_LIMITS});const now=Date.now();const location={id:'point:36.1:-95.9',name:'Fixture',latitude:36.1,longitude:-95.9,country:'US',timezone:'America/Chicago'};
 const target=verification.registerPlace('fixture-owner',{placeId:'point:36.1:-95.9',optedIn:true,location,station:{id:'KTUL',name:'Fixture station',coordinates:{latitude:36.1,longitude:-95.9},elevationM:200,distanceKm:0,elevationDifferenceM:null,selectionVersion:'fixture-v1'}});
 const forecast=ForecastSchema.parse({location,provenance:{provider:'Open-Meteo',dataset:'Fixture',classification:'modeled',retrievedAt:new Date(now).toISOString(),sourceIssuedAt:null,sourceCoordinates:location,sourceElevationM:200,attribution:'Fixture'},hours:[1,2,3].map(h=>({time:new Date(Math.floor(now/3600000)*3600000+h*3600000).toISOString(),temperatureC:20,apparentTemperatureC:20,humidityPercent:40,precipitationMm:0,precipitationProbability:10,windSpeedMs:2,windGustMs:3,windDirectionDeg:180,weatherCode:0,ordinaryWetBulbC:10})),intervalSemantics:'instant meteorology; precipitation and probability preceding hour; gust preceding-hour maximum',missingFields:[]});
 const calls:string[]=[];const worker=createVerificationWorker(verification,storage,id=>id==='fixture-owner',{getForecast:async()=>{calls.push('best_match');return forecast;},getModelForecast:async(_l,m)=>{calls.push(m);return forecast;},fetchNearbyObservations:async()=>{throw new Error('No due observations expected');}});
 try{await worker.runOnce();assert.deepEqual(calls,['best_match','gfs_seamless','ecmwf_ifs025']);assert.equal(verification.usage().forecastSnapshots,3);const score=verification.scorecard(target.targetKey);assert.equal(score.status,'pending');assert.equal(score.models.length,3);await worker.runOnce();assert.equal(calls.length,3);verification.removePlace('fixture-owner',target.placeId);assert.equal(await worker.runOnce(),'idle');}
 finally{verification.close();storage.close();}
});
