import {chromium} from 'playwright-core';
import {createServer} from 'node:http';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
import {parseClimateNormals} from '../../../packages/providers/src/climate-normals.ts';
import {ObservationsResponseSchema,observationFields} from '../../../packages/contracts/src/observations.ts';
import {VerificationRepository} from '../../../packages/verification/src/index.ts';
const now=Date.now(),location={id:'test',name:'Fixture Tulsa',latitude:36.1,longitude:-95.9,country:'US',timezone:'America/Chicago'},point={latitude:36.1,longitude:-95.9};
const normals=parseClimateNormals(await readFile((process.cwd() + '/docs/verification/climate-normals/tulsa-source.csv'),'utf8'),'USW00013968');
const time=new Date(now-60000).toISOString();const observation={sourceId:'https://api.weather.gov/stations/KTUL/observations/'+encodeURIComponent(time),time,textDescription:'Fixture',measurements:Object.fromEntries(observationFields.map(([,local])=>[local,{value:local==='temperatureC'?0:local==='dewPointC'?-5:2,qualityControl:'V',qualityMeaning:'verified_pass_levels_1_2_3'}])),missingFields:[]};
const station={stationId:'KTUL',name:'Fixture station',coordinates:point,elevationM:200,distanceKm:0,sourceUrl:'https://api.weather.gov/stations/KTUL',latestObservationTime:time,observations:[observation]};
const observed=ObservationsResponseSchema.parse({status:'success',freshness:'fresh',data:{query:{...point,since:new Date(now-10800000).toISOString(),until:new Date(now).toISOString(),stationLimit:3},stations:[station],candidateCount:1,candidateSetTruncated:false,provider:'NWS',dataset:'NWS API station observations (MADIS ingest)',classification:'observed',retrievedAt:new Date(now).toISOString(),stationListSourceUrl:'https://api.weather.gov/gridpoints/TSA/1,1/stations?limit=5',selectionPolicy:'distance-ranked candidates only; no automatic representativeness selection',stationContinuity:'observations remain grouped by station; no cross-station splice',intervalSemantics:'station instants; precipitationLastHourMm is the reported preceding-hour accumulation ending at observation time',units:Object.fromEntries(observationFields.map(([,local,unit])=>[local,unit])),qualityControlSourceUrl:'https://madis.ncep.noaa.gov/madis_sfc_qc_notes.shtml',attribution:'NWS TEST FIXTURE'}});
const server=createServer(async(req,res)=>{try{const path=new URL(req.url!,'http://local').pathname;const body=await readFile('/tmp/competitive-panels-dist'+(path==='/'?'/index.html':path));res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(body);}catch{res.writeHead(404).end();}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const port=(server.address()as any).port;
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});const reports:any[]=[];
try{for(const width of [390,1440]){const repo=new VerificationRepository({path:':memory:'});let enabled=false,prefs:any=null,posts=0,outside=0;const errors:string[]=[];const context=await browser.newContext({viewport:{width,height:900},isMobile:width===390,hasTouch:width===390});await context.addInitScript('window.__name = (fn) => fn');await context.addInitScript(()=>{const id='11111111-1111-4111-8111-111111111111';localStorage.setItem('zindycast.installation.v1',JSON.stringify({id,bearer:id+'.'+'a'.repeat(43),createdAt:Date.now()-1000,expiresAt:Date.now()+86400000}));Object.defineProperty(Notification,'permission',{get:()=> 'granted',configurable:true});Object.defineProperty(navigator,'serviceWorker',{value:{getRegistration:async()=>({active:{},pushManager:{getSubscription:async()=>({toJSON:()=>({endpoint:'https://fcm.googleapis.com/fcm/send/fixture',keys:{p256dh:'B'+'a'.repeat(86),auth:'a'.repeat(22)}}),unsubscribe:async()=>true})}})},configurable:true});});
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='127.0.0.1'){outside++;return route.abort();}if(!u.pathname.startsWith('/api/'))return route.continue();const method=route.request().method();if(method==='POST')posts++;
 const status=()=>({status:'success',configured:true,publicKey:'B'+'a'.repeat(86),enabled,preferences:prefs,expiresAt:enabled?now+86400000:null,lastCheckedAt:null,lastDeliveryAt:null,lastOutcome:enabled?'not_checked':null});
 if(u.pathname==='/api/v1/notifications'){if(method==='POST'){enabled=true;prefs=route.request().postDataJSON().preferences;}return route.fulfill({json:status()});}
 if(u.pathname==='/api/v1/notifications/disable'){enabled=false;prefs=null;return route.fulfill({json:{status:'success'}});}
 if(u.pathname==='/api/v1/observations')return route.fulfill({json:observed});
 if(u.pathname==='/api/v1/climate-normals')return route.fulfill({json:{status:'success',freshness:'fresh',data:normals}});
 if(u.pathname==='/api/v1/verification/places'){if(method==='POST'){const p=repo.registerPlace('11111111-1111-4111-8111-111111111111',route.request().postDataJSON());return route.fulfill({json:{status:'success',place:p}});}return route.fulfill({json:{status:'success',places:repo.listPlaces('11111111-1111-4111-8111-111111111111')}});}
 if(u.pathname.startsWith('/api/v1/verification/scorecards/')){const p=repo.listPlaces('11111111-1111-4111-8111-111111111111')[0];return route.fulfill({json:{status:'success',scorecard:repo.scorecard(p.targetKey)}});}
 if(u.pathname.endsWith('/remove')){repo.removePlace('11111111-1111-4111-8111-111111111111',decodeURIComponent(u.pathname.split('/').at(-2)!));return route.fulfill({json:{status:'success'}});}
 return route.fulfill({status:503,json:{status:'error',code:'provider_error',message:'Fixture unavailable'}});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}`);await page.getByRole('button',{name:'Enable warning notifications'}).waitFor();await page.getByRole('checkbox',{name:/Fixture Tulsa/}).check();await page.getByRole('button',{name:'Enable warning notifications'}).click();try{await page.getByText('Enabled for this installation.',{exact:false}).waitFor({timeout:5000});}catch(e){console.log(await page.locator('body').innerText());throw e;}await page.getByRole('button',{name:'Disable notifications',exact:true}).click();await page.getByRole('button',{name:'Enable warning notifications'}).waitFor();
 await page.getByRole('button',{name:'Load nearby observations',exact:true}).click();await page.getByLabel('Observation station').selectOption('KTUL');await page.getByRole('definition').filter({hasText:'32°'}).waitFor();
 await page.getByLabel('Normals station ID').fill('USW00013968');await page.getByRole('button',{name:'Load 30-year averages'}).click();await page.getByRole('table',{name:'Monthly 30-year averages'}).waitFor();
 await page.getByRole('button',{name:'Choose a reference station'}).click();await page.getByLabel('Reference station').selectOption('KTUL');await page.getByRole('button',{name:'Start measuring accuracy'}).click();await page.getByRole('button',{name:'Stop measuring this place'}).waitFor();await page.getByRole('table',{name:'Average forecast error'}).waitFor();await page.getByRole('button',{name:'Stop measuring this place'}).click();await page.getByRole('button',{name:'Choose a reference station'}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);assert.equal(outside,0);assert.equal(posts,4);await page.screenshot({path:`/tmp/competitive-panels-${width}.png`,fullPage:true});reports.push({width,posts,outside,errors,passed:true});await context.close();repo.close();}}
finally{await browser.close();server.close();}await writeFile('/tmp/competitive-panels-browser-results.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
