import {climateFields,type ClimateResult,type ClimateDetail} from '@zindycast/contracts';
const cell=(value:unknown)=>{let s=value==null?'':String(value);if(typeof value==='string'&&/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
const csv=(rows:unknown[][])=>rows.map(row=>row.map(cell).join(',')).join('\r\n');
function save(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function climateSummaryCsv(r:ClimateResult){const rows:unknown[][]=[['city','timezone','period','field','unit','mean_complete_days','average_daily_high','average_daily_low','min','min_time_utc','max','max_time_utc','complete_days','expected_days','available_complete_day_mean','available_sum','complete_total','calculation_version','wet_days_ge_1mm','wet_days_unknown','cloud_day_counts_0_5_25_50_69_87_100','cloud_days_unknown','wet_bulb_p50_C','wet_bulb_p90_C','wet_bulb_p95_C','source_retrieved_at']];for(const city of r.locations)for(const period of [city.overview,...city.monthly])for(const f of climateFields){const m=period.metrics[f];rows.push([city.location.name,city.location.timezone,period.key,f,m.unit,m.mean,m.avgDailyHigh,m.avgDailyLow,m.min?.value,m.min?.time,m.max?.value,m.max?.time,m.validDays,m.expectedDays,m.availableCompleteDays.mean,m.sumAvailable,m.total,r.calculationVersion,period.precipitationDays.qualifying,period.precipitationDays.unknown,period.cloudDays.counts.join('|'),period.cloudDays.unknown,period.wetBulbDistribution.p50,period.wetBulbDistribution.p90,period.wetBulbDistribution.p95,city.sources.map(s=>s.retrievedAt).join('|')]);}return csv(rows);}
export function climateDetailCsv(d:ClimateDetail){return csv([['city','timezone','time_utc',...climateFields,'weatherCode','missing_fields','source_retrieved_at'],...d.hours.map(h=>[d.location.name,d.location.timezone,h.time,...climateFields.map(f=>h[f]),h.weatherCode,h.missingFields.join('|'),d.sources.map(s=>s.retrievedAt).join('|')])]);}
export function downloadClimateSummary(r:ClimateResult){save('zindycast-climate-summary.csv',climateSummaryCsv(r));}
export function downloadClimateDetail(d:ClimateDetail){save('zindycast-climate-hourly.csv',climateDetailCsv(d));}
export function climateDailyCsv(d:ClimateDetail){return csv([['city','timezone','local_date','field','unit','mean','min','max','complete','valid_slots','expected_slots','available_sum','complete_total'],...d.days.flatMap(day=>climateFields.map(f=>{const m=day.metrics[f];const unit=f.endsWith('C')?'°C':f==='windSpeedMs'?'m/s':f==='precipitationMm'?'mm':f==='sunshineDurationSeconds'?'s':'%';return [d.location.name,d.location.timezone,day.date,f,unit,m.mean,m.min,m.max,m.complete,m.validSlots,m.expectedSlots,m.sumAvailable,m.total];}))]);}
export function downloadClimateDaily(d:ClimateDetail){save('zindycast-climate-daily.csv',climateDailyCsv(d));}
