import {Button} from '@mui/material';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import type {Location} from '@zindycast/contracts';
import {type ObservationsResponse,type ObservationStation} from '../../../packages/contracts/src/observations';
import {ClimateNormalsSchema,type ClimateNormals} from '../../../packages/contracts/src/climate-normals';
import {StationDiscovery} from './station-discovery';
import {requestJson} from './request';
import {temperature,speed,rain,type Units} from './weather';

import {parseObservedResponse,acceptedObservationValue} from './observed-current';
export {parseObservedResponse} from './observed-current';
/** Measurements remain in their own station card; never replace modeled weather silently. */
export function ObservationPanel({location,online,units,shared}:{location:Location;online:boolean;units:Units;shared?:{data:ObservationsResponse|null;error:string;busy:boolean;refresh:()=>void}}) {
 const [localData,setData]=useState<ObservationsResponse|null>(null),[localError,setError]=useState(''),[localBusy,setBusy]=useState(false),[station,setStation]=useState('');const abort=useRef<AbortController|null>(null);
 useEffect(()=>{abort.current?.abort();setData(null);setStation('');setError('');setBusy(false);return()=>abort.current?.abort();},[location.latitude,location.longitude,online]);
 const data=shared?shared.data:localData,error=shared?shared.error:localError,busy=shared?shared.busy:localBusy;
 async function load(){if(busy||!online)return;if(shared){shared.refresh();return;}const c=new AbortController();abort.current=c;setBusy(true);setError('');try{const r=parseObservedResponse(await requestJson(`/api/v1/observations?${new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude)})}`,c.signal),location);if(!c.signal.aborted){setData(r);setStation('');}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Observations unavailable.');}finally{if(!c.signal.aborted)setBusy(false);}}
 const selected=data?.data.stations.find(s=>s.stationId===station);
 return <section aria-labelledby="observations-title"><h2 id="observations-title">Nearby weather stations</h2><p>Compare the forecast with a station reading. Distance alone does not establish how well a station represents this place.</p><Button disabled={!online||busy} onClick={()=>void load()}>{busy?'Loading stations…':'Load nearby observations'}</Button>{!online&&<p>Reconnect to load station readings.</p>}{error&&<p role="alert">{error}</p>}
 {online&&data&&<>{!data.data.stations.length?<p>No nearby readings were available.</p>:<label>Observation station <select value={station} onChange={e=>setStation(e.target.value)}><option value="">Choose a station</option>{data.data.stations.map(s=><option key={s.stationId} value={s.stationId}>{s.name} · {s.distanceKm.toFixed(1)} km</option>)}</select></label>}{selected&&<StationReading station={selected} units={units} stale={data.freshness==='stale'}/>}<details><summary>Observation source</summary><p>{data.data.attribution} Retrieved {new Date(data.data.retrievedAt).toLocaleString()}. The main card uses the nearest available station within 25 km whose latest temperature passes source quality checks and is no more than 90 minutes old. These limits do not guarantee the same conditions at your address. Source quality flags remain attached to each measurement. No readings from different stations are merged.</p></details></>}
 </section>;
}
function StationReading({station,units,stale}:{station:ObservationStation;units:Units;stale:boolean}) {
 const o=station.observations[0],old=!o||Date.now()-Date.parse(o.time)>3600000;const accepted=(key:'temperatureC'|'dewPointC'|'windSpeedMs')=>{return acceptedObservationValue(o,key);};
 return <article><h3>{station.name}</h3>{station.observationHistoryTruncated&&<p className="subtle">Showing the latest available page of station readings.</p>}<p>{station.stationId} · {station.distanceKm.toFixed(1)} km away · Elevation {station.elevationM===null?'unavailable':`${Math.round(station.elevationM)} m`}</p>{o?<><p>{stale||old?'Older observation':'Station observation'} · {new Date(o.time).toLocaleString()}</p><dl><dt>Air temperature</dt><dd>{temperature(accepted('temperatureC'),units)}</dd><dt>Dew point</dt><dd>{temperature(accepted('dewPointC'),units)}</dd><dt>Wind</dt><dd>{speed(accepted('windSpeedMs'),units)}</dd></dl><details><summary>Reading quality</summary><p>Only readings with passing source quality checks are shown above. A passing flag does not establish neighborhood representativeness.</p>{(['temperatureC','dewPointC','windSpeedMs']as const).map(k=><p key={k}>{k}: {o.measurements[k].qualityMeaning??'Quality not supplied'}</p>)}</details></>:<p>No recent observations from this station.</p>}</article>;
}

export function ClimateNormalsPanel({online,units}:{online:boolean;units:Units}) {
 const [id,setId]=useState(''),[result,setResult]=useState<ClimateNormals|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const abort=useRef<AbortController|null>(null);
 useEffect(()=>{if(!online){abort.current?.abort();setResult(null);setBusy(false);}return()=>abort.current?.abort();},[online]);
 function choose(value:string){abort.current?.abort();setId(value);setResult(null);setBusy(false);setError('');}
 async function load(){if(busy||!online||!/^US[A-Z0-9]{9}$/.test(id))return;const c=new AbortController();abort.current=c;setBusy(true);setError('');setResult(null);try{const r=z.object({status:z.literal('success'),freshness:z.literal('fresh'),data:ClimateNormalsSchema}).parse(await requestJson(`/api/v1/climate-normals?stationId=${encodeURIComponent(id)}`,c.signal));if(r.data.stationId!==id)throw new Error('Station normals do not match the selection.');if(!c.signal.aborted)setResult(r.data);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Normals unavailable.');}finally{if(!c.signal.aborted)setBusy(false);}}
 return <section aria-labelledby="normals-title"><h2 id="normals-title">Typical weather · 1991–2020</h2><p>NOAA’s 30-year station averages provide a long-term reference, separate from the recent-year city comparisons.</p><StationDiscovery online={online} onChoose={choose}/><label>Normals station ID <input value={id} onChange={e=>choose(e.target.value.toUpperCase())} maxLength={11}/></label><Button disabled={!online||busy||!/^US[A-Z0-9]{9}$/.test(id)} onClick={()=>void load()}>{busy?'Loading normals…':'Load 30-year averages'}</Button>{error&&<p role="alert">{error}</p>}{online&&result&&<><h3>{result.stationName}</h3><p>Station {result.stationId} · 1991–2020 baseline · Station-derived averages, including NOAA’s adjustments and estimates.</p><div role="region" aria-label="Scrollable results table" tabIndex={0} style={{overflowX:'auto'}}><table><caption>Monthly 30-year averages</caption><thead><tr><th>Month</th><th>Average high</th><th>Average low</th><th>Mean temperature</th><th>Precipitation</th></tr></thead><tbody>{result.months.map(m=><tr key={m.month}><th>{new Intl.DateTimeFormat('en',{month:'short',timeZone:'UTC'}).format(new Date(Date.UTC(2020,m.month-1,15)))}</th>{([m.averageHighC,m.averageLowC,m.meanC,m.precipitationMm]).map((v,i)=><td key={i}>{i===3?rain(v.value,units):temperature(v.value,units)}{v.completenessFlag&&v.completenessFlag!=='S'?<small> · {({R:'Representative',P:'Provisional',E:'Estimated'}as Record<string,string>)[v.completenessFlag]}</small>:null}</td>)}</tr>)}</tbody></table></div><details><summary>Source and completeness</summary><p>Standard normals meet NOAA’s data-availability standard; they do not imply 30 years of complete unadjusted measurements. Nonstandard values are labeled in the table.</p><p>Station position: {result.latitude}, {result.longitude}; elevation {result.elevationM??'unavailable'} m. <a href={result.sourceUrl}>NOAA source CSV</a> · retrieved {new Date(result.retrievedAt).toLocaleString()}.</p><table><caption>Years contributing by month</caption><thead><tr><th>Month</th><th>High</th><th>Low</th><th>Mean</th><th>Precipitation</th></tr></thead><tbody>{result.months.map(m=><tr key={m.month}><th>{m.month}</th>{[m.averageHighC,m.averageLowC,m.meanC,m.precipitationMm].map((v,i)=><td key={i}>{v.years??'Unavailable'} · {v.completenessFlag||'Missing'}{v.measurementFlag?` / ${v.measurementFlag}`:''}</td>)}</tr>)}</tbody></table></details></>}
 </section>;
}

import {VerificationPlacesResponseSchema,VerificationPlaceResponseSchema,VerificationScorecardResponseSchema,type VerificationPlace,type VerificationScorecard} from '../../../packages/contracts/src/verification';
import {installationStore} from './comparison-model';
export function AccuracyPanel({location,online,units}:{location:Location;online:boolean;units:Units}) {
 const [places,setPlaces]=useState<VerificationPlace[]>([]),[stations,setStations]=useState<ObservationStation[]>([]),[selected,setSelected]=useState(''),[score,setScore]=useState<VerificationScorecard|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const abort=useRef<AbortController|null>(null),pending=useRef(false),store=useRef<ReturnType<typeof installationStore>|null>(null);const access=()=>store.current??=installationStore(localStorage);
 const current=places.find(p=>p.location.latitude===location.latitude&&p.location.longitude===location.longitude&&p.location.timezone===location.timezone);
 useEffect(()=>{abort.current?.abort();setPlaces([]);setStations([]);setScore(null);setSelected('');setError('');setBusy(false);return()=>abort.current?.abort();},[location.latitude,location.longitude,location.timezone,online]);
 async function action(task:(c:AbortController)=>Promise<void>){if(pending.current||!online)return;pending.current=true;const c=new AbortController();abort.current=c;setBusy(true);setError('');try{await task(c);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Accuracy service unavailable.');}finally{pending.current=false;if(!c.signal.aborted)setBusy(false);}}
 async function refresh(c:AbortController){const bearer=access().existing(Date.now());if(!bearer){setPlaces([]);return;}const r=VerificationPlacesResponseSchema.parse(await requestJson('/api/v1/verification/places',c.signal,20000,{bearer}));if(c.signal.aborted)return;setPlaces(r.places);const p=r.places.find(p=>p.location.latitude===location.latitude&&p.location.longitude===location.longitude&&p.location.timezone===location.timezone);if(!p){setScore(null);return;}const s=VerificationScorecardResponseSchema.parse(await requestJson(`/api/v1/verification/scorecards/${encodeURIComponent(p.placeId)}`,c.signal,20000,{bearer}));if(s.scorecard.place.targetKey!==p.targetKey||s.scorecard.place.placeId!==p.placeId)throw new Error('Scorecard does not match the selected place.');if(!c.signal.aborted)setScore(s.scorecard);}
 async function find(c:AbortController){const r=parseObservedResponse(await requestJson(`/api/v1/observations?${new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude)})}`,c.signal),location);if(!c.signal.aborted){setStations(r.data.stations);setSelected('');}}
 async function enable(c:AbortController){const s=stations.find(s=>s.stationId===selected);if(!s)throw new Error('Choose a reference station first.');const bearer=access().existing(Date.now())??(navigator.locks?await navigator.locks.request('zindycast.installation-registration',{signal:c.signal},()=>access().ensure(c.signal)):null);if(!bearer)throw new Error('This browser cannot safely register this installation.');
 const placeId=`point:${location.latitude}:${location.longitude}`;
 const input={placeId,optedIn:true,location:{...location,id:placeId},station:{id:s.stationId,name:s.name,coordinates:s.coordinates,elevationM:s.elevationM,distanceKm:s.distanceKm,elevationDifferenceM:null,selectionVersion:'user-selected-nws-v1'}};
 VerificationPlaceResponseSchema.parse(await requestJson('/api/v1/verification/places',c.signal,20000,{method:'POST',bearer,body:input}));if(!c.signal.aborted)await refresh(c);}
 async function remove(c:AbortController){if(!current)return;const bearer=access().existing(Date.now());if(!bearer)throw new Error('Installation access is required.');await requestJson(`/api/v1/verification/places/${encodeURIComponent(current.placeId)}/remove`,c.signal,20000,{method:'POST',bearer});if(!c.signal.aborted)await refresh(c);}
 return <section aria-labelledby="accuracy-title"><h2 id="accuracy-title">Forecast accuracy · {location.name}</h2><p>Measure forecasts against a station over time. New scorecards start empty; results become useful as weather and observations arrive.</p><div className="actions"><Button disabled={!online||busy} onClick={()=>void action(refresh)}>Load accuracy scorecard</Button>{!current&&<Button disabled={!online||busy} onClick={()=>void action(find)}>Choose a reference station</Button>}</div>
 {error&&<p role="alert">{error}</p>}{!online&&<p>Reconnect to manage or load this scorecard.</p>}
 {online&&!current&&stations.length>0&&<><label>Reference station <select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a station</option>{stations.map(s=><option key={s.stationId} value={s.stationId}>{s.name} · {s.distanceKm.toFixed(1)} km · elevation {s.elevationM??'unknown'} m</option>)}</select></label><p>By starting, you allow this server to collect forecasts and station observations for this fixed place in the background. A station may differ from your neighborhood. Up to five monitored places per installation.</p><Button disabled={busy||!selected} onClick={()=>void action(enable)}>Start measuring accuracy</Button></>}
 {online&&current&&<><p>Measuring against {current.station.name} ({current.station.id}). This keeps the existing forecast as the baseline.</p><Button disabled={busy} onClick={()=>void action(remove)}>Stop measuring this place</Button></>}
 {online&&score&&<><p role="status">{score.reason}</p><p>{score.evidence.archivedSnapshots} forecast snapshots · {score.evidence.distinctValidDays} days represented. Early results are preliminary and may not represent other seasons or extreme weather.</p><div role="region" aria-label="Scrollable results table" tabIndex={0} style={{overflowX:'auto'}}><table><caption>Average forecast error · lower is better</caption><thead><tr><th>Forecast source</th><th>How far ahead</th><th>Temperature error</th><th>Compared readings</th><th>Wind error</th><th>Rain probability score</th></tr></thead><tbody>{score.models.flatMap(m=>m.horizons.map(h=><tr key={`${m.model.id}-${h.horizon}`}><th>{m.model.role==='baseline'?'Current forecast':m.model.requestedModel}</th><td>{h.horizon}</td><td>{h.all.temperature.mae===null?'Collecting data':`${(h.all.temperature.mae*(units==='us'?1.8:1)).toFixed(1)} ${units==='us'?'°F':'°C'}`}</td><td>{h.all.temperature.paired}</td><td>{h.all.windSpeed.mae===null?'Collecting data':speed(h.all.windSpeed.mae,units)}</td><td>{h.all.rain.brierScore===null?'Collecting compatible data':h.all.rain.brierScore.toFixed(3)}</td></tr>))}</tbody></table></div>
 <details><summary>How accuracy is measured</summary><p>Temperature and wind show mean absolute error. Rain uses the Brier score for the provider’s hourly precipitation event, not whole-day probability. Only matching periods and accepted station quality flags contribute. Missing observations are not counted as successes.</p><p>Forecasts are saved before their valid time. One forecast per source, timestamp and lead-time group is scored. Twenty percent of timestamps are held out for evaluation; no automatic model winner or correction is selected from these early results.</p><table><caption>Data support by lead time</caption><thead><tr><th>Source / lead</th><th>Missing temperature observations</th><th>Excluded temperature quality</th><th>Held-out temperature pairs</th><th>Rain pairs</th><th>Rain misses / false alarms</th></tr></thead><tbody>{score.models.flatMap(m=>m.horizons.map(h=><tr key={`${m.model.id}-${h.horizon}`}><th>{m.model.requestedModel} / {h.horizon}</th><td>{h.all.temperature.missingObservation}</td><td>{h.all.temperature.excludedQuality}</td><td>{h.holdout.temperature.paired}</td><td>{h.all.rain.paired}</td><td>{h.all.rain.misses} / {h.all.rain.falseAlarms}</td></tr>))}</tbody></table></details></>}
 </section>;
}
