import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Button,Card,CircularProgress,Table,TableBody,TableCell,TableContainer,TableHead,TablePagination,TableRow,ToggleButton,ToggleButtonGroup} from '@mui/material';
import {WetBulbTrackerResponseSchema,type WetBulbTrackerRecord} from '@zindycast/contracts';
import {TULSA_WBGT_SCALE,tulsaWbgtPosition} from '@zindycast/heat';
import {WeatherBackdrop,weatherKind,weatherKindAtmosphere} from './weather-appearance';

const f=(c:number|null,digits=1)=>c==null?'—':`${(c*9/5+32).toFixed(digits)}°F`;
const band=(c:number|null)=>{const p=tulsaWbgtPosition({metric:'wbgt',valueC:c},[20,38]);return p.status!=='positioned'?'Unavailable':p.bandIndex==null?`At ${p.boundaryF}°F boundary`:`${TULSA_WBGT_SCALE.labels[p.bandIndex]}°F`;};
const bandIndex=(c:number|null)=>{const p=tulsaWbgtPosition({metric:'wbgt',valueC:c},[20,38]);return p.status==='positioned'?p.bandIndex:null;};
const markerPosition=(c:number|null)=>{const p=tulsaWbgtPosition({metric:'wbgt',valueC:c},[20,38]);if(p.status!=='positioned')return null;if(p.bandIndex!=null)return (p.bandIndex+.5)*20;const boundary=TULSA_WBGT_SCALE.boundariesF.indexOf(p.boundaryF as 80|85|88|90);return boundary<0?null:(boundary+1)*20;};
const csvCell=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;
export function trackerCsv(records:WetBulbTrackerRecord[]){const keys:([keyof WetBulbTrackerRecord,string])[]=[['recordedAt','recorded_at'],['sourceValidTime','source_valid_time'],['wbgtC','wet_bulb_globe_temperature_c'],['temperatureC','air_temperature_c'],['apparentTemperatureC','feels_like_c'],['dewPointC','dew_point_c'],['humidityPercent','humidity_percent'],['windSpeedMs','wind_speed_m_s'],['precipitationProbability','rain_chance_percent'],['isDay','is_day'],['provider','provider'],['classification','classification'],['retrievedAt','provider_retrieved_at']];return [keys.map(k=>csvCell(k[1])).join(','),...records.map(r=>keys.map(k=>csvCell(r[k[0]])).join(','))].join('\n');}

export function WetBulbTrackerPage(){const [data,setData]=useState<ReturnType<typeof WetBulbTrackerResponseSchema.parse>|null>(null),[error,setError]=useState(''),[days,setDays]=useState(7),[page,setPage]=useState(0),[reload,setReload]=useState(0),[captureMessage,setCaptureMessage]=useState(''),[capturing,setCapturing]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/v1/wet-bulb-tracker',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error(r.status===404?'This private tracker is not enabled.':'Tracker data could not be loaded.');return WetBulbTrackerResponseSchema.parse(await r.json());}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort();},[reload]);
 const records=useMemo(()=>data?.records.filter(r=>Date.parse(r.recordedAt)>=Date.now()-days*86400000)??[],[data,days]);const latest=records[0];const values=records.flatMap(r=>r.wbgtC==null?[]:[r.wbgtC]);const avg=values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
 const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([trackerCsv(records)],{type:'text/csv'}));a.download=`wet-bulb-tracker-${days}d.csv`;a.click();URL.revokeObjectURL(a.href);};
 const capture=async()=>{setCapturing(true);setCaptureMessage('');try{const response=await fetch('/api/v1/wet-bulb-tracker/capture',{method:'POST',headers:{'Content-Type':'application/json','X-ZindyCast-Request':'1'},body:'{}'});const body=await response.json().catch(()=>null);if(response.status===409)setCaptureMessage('Same result as the latest record — nothing new was saved.');else if(!response.ok)throw new Error();else{setCaptureMessage('New result saved.');setReload(value=>value+1);}}catch{setCaptureMessage('Could not capture the current result. Try again.');}finally{setCapturing(false);}};
 if(error)return <main className="tracker-shell"><Alert severity="info">{error}</Alert></main>;if(!data)return <main className="tracker-shell"><CircularProgress aria-label="Loading tracker"/></main>;
 const sceneKind=weatherKind(latest?.weatherCode);const skyPhase=latest?.isDay===0?'night':latest?.isDay===1?'day':'neutral';
 return <div className="app-shell tracker-scene" data-motion="running" data-weather-kind={sceneKind} data-weather={weatherKindAtmosphere(sceneKind,latest?.isDay)} data-sky-phase={skyPhase}><WeatherBackdrop/><main className="tracker-shell"><header><p className="tracker-eyebrow">PRIVATE WEATHER LOG</p><h1>{data.location.name} wet bulb tracker</h1><p>Recorded every {data.cadenceMinutes} minutes · modeled outdoor estimates</p></header>
 <Card className="tracker-primary"><div><p className="tracker-eyebrow">WET BULB</p><strong>{f(latest?.wbgtC??null)}</strong><h2>{band(latest?.wbgtC??null)} reference band</h2><p>{latest?`Latest modeled outdoor estimate, recorded ${new Date(latest.recordedAt).toLocaleString([], {dateStyle:'medium',timeStyle:'short',timeZone:data.location.timezone})}.`:'No readings recorded yet.'}</p></div><div className="tracker-scale-wrap">{markerPosition(latest?.wbgtC??null)!=null&&<span className="tracker-band-marker" style={{left:`${markerPosition(latest?.wbgtC??null)}%`}} aria-label={`Current value: ${f(latest?.wbgtC??null)}, ${band(latest?.wbgtC??null)} band`}>▼</span>}<div className="tracker-reference-scale" aria-label="Wet bulb reference bands">{TULSA_WBGT_SCALE.labels.map((label,i)=><span key={label} className={`tracker-band-${i}`}>{label}</span>)}</div></div><p className="tracker-source">NWS Tulsa reference bands · Exact printed endpoints are shown as boundaries.</p></Card>
 <section className="tracker-stats"><Card><span>Latest WBGT</span><strong>{f(latest?.wbgtC??null)}</strong></Card><Card><span>{days}-day low</span><strong>{f(values.length?Math.min(...values):null)}</strong></Card><Card><span>{days}-day average</span><strong>{f(avg)}</strong></Card><Card><span>{days}-day high</span><strong>{f(values.length?Math.max(...values):null)}</strong></Card></section>
 <div className="tracker-actions"><ToggleButtonGroup exclusive value={days} onChange={(_,v)=>{if(v){setDays(v);setPage(0)}}}>{[7,30,90].map(v=><ToggleButton key={v} value={v}>{v} days</ToggleButton>)}</ToggleButtonGroup><div className="tracker-action-buttons"><Button variant="outlined" onClick={capture} disabled={capturing}>{capturing?'Capturing…':'Capture now'}</Button><Button variant="contained" onClick={download} disabled={!records.length}>Download CSV</Button></div></div>{captureMessage&&<p className="tracker-capture-message" role="status">{captureMessage}</p>}
 <TableContainer component={Card}><Table size="small"><caption>Recorded times use {data.location.timezone}.</caption><TableHead><TableRow>{['Recorded','Wet bulb','Reference band','Air','Feels like','Humidity','Wind','Rain chance'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{records.slice(page*25,page*25+25).map(r=>{const index=bandIndex(r.wbgtC);return <TableRow key={r.recordedAt}><TableCell>{new Date(r.recordedAt).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:data.location.timezone})}</TableCell><TableCell><strong>{f(r.wbgtC)}</strong></TableCell><TableCell><span className={`tracker-table-band ${index==null?'tracker-band-neutral':`tracker-band-${index}`}`}>{band(r.wbgtC)}</span></TableCell><TableCell>{f(r.temperatureC)}</TableCell><TableCell>{f(r.apparentTemperatureC)}</TableCell><TableCell>{r.humidityPercent==null?'—':`${r.humidityPercent}%`}</TableCell><TableCell>{r.windSpeedMs==null?'—':`${(r.windSpeedMs*2.23694).toFixed(1)} mph`}</TableCell><TableCell>{r.precipitationProbability==null?'—':`${r.precipitationProbability}%`}</TableCell></TableRow>})}</TableBody></Table><TablePagination component="div" count={records.length} page={page} onPageChange={(_,p)=>setPage(p)} rowsPerPage={25} rowsPerPageOptions={[25]}/></TableContainer>
 <p className="tracker-footnote">Weather by Open-Meteo · modeled estimate. Collection begins when the worker is enabled; there is no invented backfill.</p></main></div>;
}
